import shutil
from os import path, walk
from pathlib import Path

from ..services.job_creation_service import JobCreationService

from ..models.enums import FileTypes, Formats, Status, Task
from ..models.job.audio_sync_job import AudioSyncJob
from ..models.job.video_sync_job import VideoSyncJob
from . import constants
from . import console_utils as cu
from ..ui.file_dialogs import FileDialog


def get_directories():
    """Get and validate source and destination directories."""
    src_path = FileDialog.askdirectory(title="Select Source Folder")
    dst_path = FileDialog.askdirectory(title="Select Destination Folder")

    if src_path == dst_path:
        cu.print_error("Source and destination folders are the same!")
        return None, None
  
    if not path.exists(src_path):
        cu.print_error(f"Source Path {src_path} does not exist!")
        return None, None

    if not path.exists(dst_path):
        cu.print_error(f"Destination Path {dst_path} does not exist!")
        return None, None

    return src_path, dst_path


def get_files_in_directory(directory: str, formats: list[str]) -> list[str]:
    """Recursively find files matching given formats."""
    matched_files = []
    for root, _, files in walk(directory):
        matched_files.extend(
            path.join(root, name) 
            for name in files 
            if name.endswith(formats)
        )
    return matched_files


def search_directories(src_path: str, dst_path: str, task: Task) -> list[AudioSyncJob] | list[VideoSyncJob]:
    """Search directories and create jobs from matching files."""
    formats = Formats.AUDIO.value if task == Task.AUDIO_SYNC_DIR else Formats.VIDEO.value
    
    src_files = get_files_in_directory(src_path, formats)
    dst_files = get_files_in_directory(dst_path, formats)
    sub_files = (
        get_files_in_directory(src_path, Formats.SUBTITLE.value) 
        if task == Task.AUDIO_SYNC_DIR 
        else []
    )

    if validate_files(src_files, dst_files, sub_files, task):
        return _get_jobs_from_combinations(src_files, dst_files, sub_files, task)
    return []


def select_files(task: Task) -> list[AudioSyncJob] | list[VideoSyncJob]:
    """Select files via dialog and create jobs."""
    src_files = []
    dst_files = []
    sub_files = []

    if task == Task.AUDIO_SYNC_FIL:
        src_files = FileDialog.askfilenames("Select Source Audio Files", FileTypes.AUDIO.value)
        sub_files = FileDialog.askfilenames("Select Source Subtitle Files", FileTypes.SUBTITLE.value)
        dst_files = FileDialog.askfilenames("Select Sync Target Audio Files", FileTypes.AUDIO.value)

    elif task == Task.VIDEO_SYNC_FIL:
        src_files = FileDialog.askfilenames("Select Source Video Files", FileTypes.VIDEO.value)
        dst_files = FileDialog.askfilenames("Select Sync Target Video Files", FileTypes.VIDEO.value)

    if validate_files(src_files, dst_files, sub_files, task):
        return _get_jobs_from_combinations(src_files, dst_files, sub_files, task)
    return []


def validate_files(src_files: list[str], dst_files: list[str], sub_files: list[str], task: Task) -> bool:
    """Validate file counts and task requirements."""
    src_len, dst_len, sub_len = len(src_files), len(dst_files), len(sub_files)

    validations = [
        (src_len == 0, "No source files found!"),
        (dst_len == 0, "No sync target files found!"),
        (src_len != dst_len, f"Source ({src_len}) and sync target ({dst_len}) file counts don't match!"),
        (task in (Task.AUDIO_SYNC_DIR, Task.AUDIO_SYNC_FIL) and src_len != sub_len, 
        f"Audio ({src_len}) and subtitle ({sub_len}) file counts don't match!"),
    ]

    for condition, error_msg in validations:
        if condition:
            cu.print_error(error_msg)
            return False
    return True


def _get_jobs_from_combinations(src_files: list[str], dst_files: list[str], sub_files: list[str], task: Task) -> list[AudioSyncJob] | list[VideoSyncJob]:
    if task in constants.AUDIO_TASKS:
        return JobCreationService.create_audio_sync_jobs(src_files, dst_files, sub_files, task)
    else:
        return JobCreationService.create_video_sync_jobs(src_files, dst_files, task)

def clean_generated_files(job_list):
    """Delete subtitle files generated by sushi and aegisub for the specified jobs"""
    try:
        for job in job_list:
            if job.sync_status is not Status.COMPLETED: 
                continue
            
            suffixes = []
            if job.task in constants.AUDIO_TASKS:
                sub_ext = Path(job.sub_file).suffix if job.sub_file else ""
                if not sub_ext:
                    continue
                suffixes.append(f".sushi{sub_ext}")
            else:
                if job.merge_audio_encode_done: 
                    suffixes.append(f"_encode.{job.merge_audio_encode_codec.lower()}")
                sub_ext = job.src_sub_ext
                if not sub_ext:
                    continue
                suffixes.extend([f".sushi{sub_ext}", f".sushi_resampled{sub_ext}"])

            for suffix in suffixes:
                generated_file = Path(f"{job.dst_file}{suffix}")
                generated_file.unlink(missing_ok=True)
        cu.print_success("Generated files deleted successfully.")
    except OSError as e:
        cu.print_error(f"Error deleting generated files: {e}")


def clear_logs(dirpath):
    try:
        root = Path(dirpath)
        for name in ("Sushi Logs", "Merge Logs", "Aegisub Resample Logs"):
            target = root / name
            if target.exists() and target.is_dir():
                shutil.rmtree(target)
    except OSError as e:
        cu.print_error(f"Error clearing logs: {e}")