import os
import shutil
import subprocess
import sys
from importlib.util import find_spec
from pathlib import Path
from . import console_utils as cu



def is_app_installed(app_name):
    if is_app_env_var(app_name):
        return True
    
    # If running on Windows, check if executable is inside working directory 
    elif os.name == "nt" and os.path.exists(os.path.join(os.getcwd(), f"{app_name}.exe")): 
        return True
    
    return False


def is_app_env_var(app):
    try:
        subprocess.run(app, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except OSError:
        return False
    else:
        return True
    

def clear_logs(dirpath):
    try:
        for entry in os.listdir(dirpath):
            if entry in("Sushi Logs", "Merge Logs", "Aegisub Resample Logs"):
                entry_path = os.path.join(dirpath, entry)
                shutil.rmtree(entry_path)  # Recursively delete the directory
    except OSError as e:
        print(e)

def clean_generated_files(job_list):
    """Delete files generated by sushi and aegisub for the specified jobs"""
    try:
        for job in job_list:
            if job.src_sub_ext is None:
                continue

            for suffix in (
                f".sushi{job.src_sub_ext}",
                f".sushi_resampled{job.src_sub_ext}",
            ):
                generated_file = Path(f"{job.dst_file}{suffix}")
                generated_file.unlink(missing_ok=True)
        cu.print_success("Generated files deleted successfully.")
    except OSError as e:
        cu.print_error(f"Error deleting generated files: {e}")


def check_required_packages():
    _PACKAGES = ["art", "colorama", "sushi", "prettytable", "yaspin"]

    for pkg in _PACKAGES:
        if find_spec(pkg) is None:
            print(
                f"\033[91mPackage {pkg} is not installed. Install all dependencies before running the tool\033[00m"
            )
            sys.exit(1)
